server:
  port: 8001
spring:
  application:
    name: online-user
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/online_school
      username: root
      password: password
  redis:
    host: 192.168.124.131  #redis服务器
    port: 6379  #redis端口号
    database: 0 #redis数据库索引（默认为0）
    timeout: 6000ms #redis连接超时时间
    jedis:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值代表没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  #连接池中的最大空连接
        min-idle: 5 #连接池中的最小空闲连接

